Feature/icky 809
KiboSoftware/nextjs-nivel-builderio-starter-storefront pull request #1
Opened 2023-01-20 06:53 UTC by kibo-geetanshuchhabra

2023-01-23 08:37 UTC, kibo-sushant approved these changes

2023-01-24 13:34 UTC, kibo-chandradeeptalaha requested changes

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/home/LargeBanner/LargeBanner.tsx
> +              alt={backgroundImageUrl ? 'abc' : 'product-image-alt'}
What is abc here?

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/layout/AppHeader/Common/KiboHeader.tsx
>    },
Remove commented code.

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on cms/components/CmsFeaturedCategories/CmsFeaturedCategories.stories.tsx
> +Common.args = {
Should we use separate mock files for this, as it is used in another file as well?

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on cms/components/CmsVehicleInnovation/CmsVehicleInnovation.stories.tsx
> +    {
Should we use separate mock files for this, as it is used in another file as well?

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/home/LargeBanner/LargeBanner.tsx
> +                style={{ fontSize: mobileView ? '18px' : '36px' }}
use rem instead px, try to use it from theme.

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionSelect/ProductOptionSelect.spec.js
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
use absolute path.

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/product/ProductOptionSelect/ProductOptionSelect.stories.tsx
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
use absolute path.

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/common/PasswordValidation/PasswordValidation.spec.tsx
> +import theme from '../../../styles/theme'
import theme from '@/styles/theme'
Check in other files as well.

2023-01-24 13:34 UTC, kibo-chandradeeptalaha commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
use absolute path.

2023-01-27 13:18 UTC, kibo-geetanshuchhabra commented on components/home/LargeBanner/LargeBanner.tsx
> +              alt={backgroundImageUrl ? 'abc' : 'product-image-alt'}
Resolved

2023-01-27 13:18 UTC, kibo-geetanshuchhabra commented on components/layout/AppHeader/Common/KiboHeader.tsx
>    },
Resolved

2023-01-27 13:18 UTC, kibo-geetanshuchhabra commented on cms/components/CmsFeaturedCategories/CmsFeaturedCategories.stories.tsx
> +Common.args = {
Resolved

2023-01-27 13:18 UTC, kibo-geetanshuchhabra commented on cms/components/CmsVehicleInnovation/CmsVehicleInnovation.stories.tsx
> +    {
Resolved

2023-01-27 13:18 UTC, kibo-geetanshuchhabra commented on components/home/LargeBanner/LargeBanner.tsx
> +                style={{ fontSize: mobileView ? '18px' : '36px' }}
Resolved

2023-01-27 13:24 UTC, kibo-geetanshuchhabra commented on components/core/ImageGallery/ImageGallery.stories.tsx
> +import { imageGalleryData } from '../../../__mocks__/stories/imageGalleryDataMock'
This is a Fork Branch. All these changes will have to be done in the nextjs-storefront branch.

2023-01-27 13:24 UTC, kibo-geetanshuchhabra commented on components/common/PasswordValidation/PasswordValidation.spec.tsx
> +import theme from '../../../styles/theme'
This is a Fork Branch. All these changes will have to be done in the nextjs-storefront branch.

2023-01-27 13:24 UTC, kibo-geetanshuchhabra commented on components/product/ProductOptionSelect/ProductOptionSelect.stories.tsx
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
This is a Fork Branch. All these changes will have to be done in the nextjs-storefront branch.

2023-01-27 13:24 UTC, kibo-geetanshuchhabra commented on components/product/ProductOptionSelect/ProductOptionSelect.spec.js
> +import { productOptionSelectValuesMock } from '../../../__mocks__/stories/productOptionSelectMock'
This is a Fork Branch. All these changes will have to be done in the nextjs-storefront branch.

2023-01-30 15:02 UTC, kibo-kevinwatts approved these changes

2023-01-30 15:02 UTC, merged